[package]
name = "expect"
version = "0.1.0"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]

[dependencies]
futures = "0.1.17"
libc = "*"
log = "0.4.1"
mio = "*"
regex = "0.2.5"
tokio-core = "0.1.12"
tokio-io = "0.1.4"
tokio-proto = "*"
tty = "*"

[dev-dependencies]
env_logger = "0.4.3"
